# Generated by Django 2.1.1 on 2018-12-26 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaign', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank='true', max_length=210, null='true')),
                ('invoke_div', models.CharField(blank='true', max_length=200, null='true')),
                ('position', models.IntegerField(blank='true', null='true')),
                ('extra_css_class', models.CharField(blank='true', max_length=210, null='true')),
                ('is_default', models.BooleanField(blank='true', default='0')),
                ('category', models.CharField(blank='true', max_length=210, null='true')),
            ],
            options={
                'verbose_name': 'Component List',
                'verbose_name_plural': 'Component Lists',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='external_vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank='true', max_length=500, null='true')),
                ('user', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedComponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
                ('component', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='client.ComponentsList')),
            ],
        ),
        migrations.CreateModel(
            name='SetDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(blank='true', max_length=210, null='true')),
                ('values', models.CharField(blank='true', max_length=410, null='true')),
                ('user', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'verbose_name': 'Set as Default',
                'verbose_name_plural': 'Set as Defaults',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='UseAsTxtMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_txt', models.CharField(blank='true', max_length=500, null='true')),
                ('alternative_txt', models.CharField(blank='true', max_length=500, null='true')),
                ('campaign', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
            ],
        ),
    ]
