# Generated by Django 2.0.2 on 2019-01-29 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_mapping_custom_status'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadValidationComponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank='true', max_length=210, null='true')),
                ('function_name', models.CharField(blank='true', max_length=210, null='true')),
                ('position', models.IntegerField(blank='true', null='true')),
                ('is_default', models.BooleanField(default='0')),
            ],
            options={
                'verbose_name': 'Lead validation Components',
                'verbose_name_plural': 'Lead validation Components',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='SelectedLeadValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='campaign.Campaign')),
                ('component', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='client.LeadValidationComponents')),
            ],
        ),
    ]
