# Generated by Django 2.0.2 on 2019-01-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_leadvalidationcomponents_selectedleadvalidation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedleadvalidation',
            name='component',
        ),
        migrations.AddField(
            model_name='selectedleadvalidation',
            name='component_list',
            field=models.TextField(null='true'),
        ),
    ]
