# Generated by Django 2.0.2 on 2019-01-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20190129_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadersValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_list', models.TextField(null='true')),
                ('company_size', models.TextField(null='true')),
            ],
        ),
    ]
