# Generated by Django 2.0.2 on 2019-02-04 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_headersvalidation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headersvalidation',
            old_name='company_size',
            new_name='company_limit',
        ),
    ]
