# Generated by Django 2.0.2 on 2019-02-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20190204_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headersvalidation',
            name='company_limit',
            field=models.IntegerField(null='true'),
        ),
    ]
