# Generated by Django 2.1.4 on 2019-02-13 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190213_0635'),
        ('client', '0007_auto_20190207_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAccessUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ApiLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='apiaccessusers',
            name='ApiAccess',
            field=models.ManyToManyField(blank=True, related_name='recommended', to='client.ApiLinks'),
        ),
        migrations.AddField(
            model_name='apiaccessusers',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
