# Generated by Django 2.1.4 on 2019-02-26 06:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0013_auto_20190219_0754'),
        ('client', '0009_headerspecsvalidation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2019, 2, 26, 6, 20, 40, 294620))),
                ('start_date', models.DateTimeField()),
                ('data_vendor_assign', models.TextField(blank=True)),
                ('client_action', models.TextField(blank=True)),
                ('complete_status', models.TextField(blank=True)),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='campaign.Campaign')),
            ],
        ),
    ]
