# Generated by Django 2.1.4 on 2019-02-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_campaigntrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigntrack',
            name='created_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
