# Generated by Django 2.1.4 on 2019-02-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0013_auto_20190226_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigntrack',
            name='client_action_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaigntrack',
            name='complete_status_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaigntrack',
            name='data_vendor_assign_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
