# Generated by Django 2.1.4 on 2019-02-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0014_auto_20190226_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigntrack',
            name='client_action_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaigntrack',
            name='complete_status_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaigntrack',
            name='data_vendor_assign_count',
            field=models.IntegerField(default=0),
        ),
    ]
