# Generated by Django 2.1.4 on 2019-04-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_auto_20190226_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('nda_mnda_document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('msa_document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('gdpr_document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('dpa_document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('io_document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
