# Generated by Django 2.1 on 2019-04-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0017_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setdefault',
            name='values',
            field=models.TextField(blank='true', null='true'),
        ),
    ]
