# Generated by Django 2.1.4 on 2019-04-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_vendor', '0002_client_vendor_media_kit'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_assesment',
            name='dpa_aggrement_path',
            field=models.FileField(blank=True, null=True, upload_to='Client_Vendor/Data_assesments'),
        ),
        migrations.AddField(
            model_name='data_assesment',
            name='gdpr_aggrement_path',
            field=models.FileField(blank=True, null=True, upload_to='Client_Vendor/Data_assesments'),
        ),
        migrations.AddField(
            model_name='data_assesment',
            name='io_aggrement_path',
            field=models.FileField(blank=True, null=True, upload_to='Client_Vendor/Data_assesments'),
        ),
        migrations.AddField(
            model_name='data_assesment',
            name='msa_aggrement_path',
            field=models.FileField(blank=True, null=True, upload_to='Client_Vendor/Data_assesments'),
        ),
        migrations.AddField(
            model_name='data_assesment',
            name='nda_aggrement_path',
            field=models.FileField(blank=True, null=True, upload_to='Client_Vendor/Data_assesments'),
        ),
    ]
